name: Build and deploy Astro app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Upload to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          sftp_only: true
          port: 22
          local_path: dist/*
          remote_path: /var/www/html
